### ISSUE TITLE
建议重构至UWP应用

### ISSUE THREAD

**Issue by xiaoli8848** [Melon-Studio/DarkMode#10]
这是一个仅面向Windows 11的系统实用工具类项目，我觉得使用UWP + WinUI 2会大大增强其与Windows的集成度、界面美观度和代码简洁度，毕竟UWP可以有非常方便的本地化实现、程序偏好设置实现，也更加符合Windows 11的设计语言。

**Comment by 6get-xiaofan** [comment]
当前暂不打算重构至UWP应用
