### ISSUE TITLE
Wallpaper Engine 转换壁纸失败

### ISSUE THREAD

**Issue by Junital** [Melon-Studio/DarkMode#11]
**OS : windows 11**

自己在steam下载的wallpaper engine，但是在浅色和深色系统变换的时候，wallpaper engine并没有发生改变

**Comment by 6get-xiaofan** [comment]
建议录制一个GIF放出来，否则我无法确定问题所在

**Comment by 6get-xiaofan** [comment]
Issues that have not been answered for a long time will be closed.
