### ISSUE TITLE
在不授予管理员权限的情况下设置开机启动报错

### ISSUE THREAD

**Issue by Steve5wutongyu6** [Melon-Studio/DarkMode#13]
[![vPaMZt.jpg](https://s1.ax1x.com/2022/07/29/vPaMZt.jpg)](https://imgtu.com/i/vPaMZt)

希望能在首次运行时提醒以管理员权限运行，或者在设置开机启动时要求提升权限

**Comment by 6get-xiaofan** [comment]
所以在管理员模式下设置开机自启
