### ISSUE TITLE
壁纸无法自动切换

### ISSUE THREAD

**Issue by konstant2016** [Melon-Studio/DarkMode#15]
描述：设置好壁纸和时间后，手动在系统设置里面切换时间，只有主题发生了变化，壁纸并没有跟随变化
软件版本：DarkMode-for-Windows-x64-v1.6.0-repair
系统版本：Windows 11 专业版 22H2  22621.232
尝试操作：把壁纸放在纯英文路径下，此问题依旧存在

**Comment by 6get-xiaofan** [comment]
尝试重启Windows资源管理器试试

**Comment by konstant2016** [comment]
刚试了一下重启资源管理器，依然不行，我还尝试了注销和重启电脑，都是只能自动切换主题，不能自动切换壁纸，我尝试了手动切换主题和设置壁纸，都是OK的。系统是从微软官网加入preview计划后下载的镜像，不是精简版系统，电脑上也没有安装360之类的安全软件，就很迷惑了，不知道为啥（手动狗头）

**Comment by 6get-xiaofan** [comment]
什么类型的壁纸
打开注册表编辑器HKEY_CURRENT_USER\Control Panel\Desktop
看一下WallPaper键的对应值是什么
你尝试管理员模式运行一下

**Comment by konstant2016** [comment]
不是wallpaper，是两张png格式的图片，软件设置界面如图，用的就是管理员模式运行的
![image](https://user-images.githubusercontent.com/28941281/182021885-30f81fd1-379b-4321-ab9a-ad70c6f76273.png)
我先这么用着吧，除了壁纸以外，切换主题还是OK的，老哥下个版本可以尝试添加一些运行日志，我到时候把日志贴上来方便排查

**Comment by 6get-xiaofan** [comment]
尝试放到C盘以外的磁盘，c盘可能权限不足无法切换

**Comment by 6get-xiaofan** [comment]
https://github.com/Melon-Studio/DarkMode/releases/tag/v1.6.5
