### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Oo-Fly-oO** [Melon-Studio/DarkMode#16]
1“开机自启动”目前只能右键任务栏图标勾选，可不可以把它放在设置里面？
2“语言”选项卡放在最后感觉会好看一点
3建议单击任务栏里的图标就能打开设置页面，不需要右键打开

**Comment by 6get-xiaofan** [comment]
https://github.com/Melon-Studio/DarkMode/releases/tag/v1.6.5
