### ISSUE TITLE
[Bug]无法自动更换壁纸

### ISSUE THREAD

**Issue by YuLiu-lab** [Melon-Studio/DarkMode#21]
我设置了原生模式下的浅色和深色壁纸，并保存了。
![Snipaste_2022-08-05_19-34-31](https://user-images.githubusercontent.com/48347233/183069469-f0759277-fa89-4abf-8f09-7591a60954b9.jpg)
这两张壁纸分别是Windows自带的深色和浅色壁纸
![Snipaste_2022-08-05_19-35-05](https://user-images.githubusercontent.com/48347233/183069544-89208ff2-f875-472d-8ab7-623425809521.jpg)
但是它并没有生效，我设置之后也尝试过重启，依旧不生效，如下图，状态栏是深色的，但壁纸是浅色的
![Snipaste_2022-08-05_19-35-16](https://user-images.githubusercontent.com/48347233/183069603-44c4a2ae-57ba-48c4-997e-c2b142834375.jpg)
我的电脑上安装了wallpaper engine，但没有启动，不知道这会不会是引起无法更换壁纸的原因？

**Comment by 6get-xiaofan** [comment]
不要放到C盘试试，读取权限不足可能访问不了

**Comment by YuLiu-lab** [comment]
我放到了D盘，还是不行

**Comment by 6get-xiaofan** [comment]
打开注册表编辑器HKEY_CURRENT_USER\Control Panel\Desktop
看一下WallPaper键的对应值是什么
你尝试管理员模式运行一下

**Comment by ShaoZhu-1** [comment]
放其他盘确实可行

**Comment by YuLiu-lab** [comment]
WallPaper键的值是D:\Pictures\img19.jpg，软件是以管理员模式运行的，版本是最新的1.6.5.0，windows版本是Win11 21H2 22000.795，不知道这是否有帮助。

**Comment by YuLiu-lab** [comment]
> 放其他盘确实可行

这样子？那可能是我电脑的问题，我折腾看看。

**Comment by 6get-xiaofan** [comment]
> WallPaper键的值是D:\Pictures\img19.jpg，软件是管理员模式运行的，版本是最新的1.6.5.0，windows版本是Win11 21H2 22000.795，不知道这是否有帮助。

D:\Pictures\img19.jpg，对应你发的截图中的深色壁纸，所以软件是切换成功的，所以是正常的，后面我会将软件需要的权限级别提升一下，此问题就能完美解决

**Comment by YuLiu-lab** [comment]
好的，但是壁纸确实没有生效，但此时我重启之后，壁纸就生效了。

**Comment by 6get-xiaofan** [comment]
你的系统问题
