### ISSUE TITLE
22H2版本windows运行时显示发生未处理异常

### ISSUE THREAD

**Issue by h88782481** [Melon-Studio/DarkMode#22]
![image](https://user-images.githubusercontent.com/54714341/185279022-ca3964fd-44f1-40b0-b690-c4c5fa0c3a6c.png)

**Comment by 6get-xiaofan** [comment]
请提供详细信息

**Comment by h88782481** [comment]
> 

没有其他的信息，打开之后就弹这个

**Comment by 6get-xiaofan** [comment]
能把报错信息完整复制吗？只有这么一点没办法看啊

**Comment by h88782481** [comment]
************** 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 DarkMode.Form1.timer1_Tick(Object sender, EventArgs e)
   在 System.Windows.Forms.Timer.OnTick(EventArgs e)
   在 System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
DarkMode
    程序集版本:1.6.5.0
    Win32 版本:1.6.5
    基本代码:file:///G:/DarkMode-for-Windows-x64-v1.6.5.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Management
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
Microsoft.Toolkit.Uwp.Notifications
    程序集版本:7.1.0.0
    Win32 版本:1.6.5
    基本代码:file:///G:/DarkMode-for-Windows-x64-v1.6.5.exe
----------------------------------------
Windows.UI
    程序集版本:255.255.255.255
    Win32 版本:10.0.10011.16384
    基本代码:file:///C:/WINDOWS/system32/WinMetadata/Windows.UI.winmd
----------------------------------------
System.Runtime.InteropServices.WindowsRuntime
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.WindowsRuntime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.WindowsRuntime.dll
----------------------------------------
Windows.Data
    程序集版本:255.255.255.255
    Win32 版本:10.0.10011.16384
    基本代码:file:///C:/WINDOWS/system32/WinMetadata/Windows.Data.winmd
----------------------------------------
Windows.ApplicationModel
    程序集版本:255.255.255.255
    Win32 版本:10.0.10011.16384
    基本代码:file:///C:/WINDOWS/system32/WinMetadata/Windows.ApplicationModel.winmd
----------------------------------------
Windows.Storage
    程序集版本:255.255.255.255
    Win32 版本:10.0.10011.16384
    基本代码:file:///C:/WINDOWS/system32/WinMetadata/Windows.Storage.winmd
----------------------------------------
System.Runtime
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
DynamicComActivator
    程序集版本:0.0.0.0
    Win32 版本:1.6.5
    基本代码:file:///G:/DarkMode-for-Windows-x64-v1.6.5.exe
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

**Comment by 6get-xiaofan** [comment]
2.0版本重构中，此问题暂时关闭
