### ISSUE TITLE
22H2 直接修改SystemUseLightTheme后任务栏颜色异常

### ISSUE THREAD

**Issue by oreomaker** [Melon-Studio/DarkMode#3]
**系统版本**
版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2022/‎5/‎13
操作系统版本	22622.436
体验	Windows Feature Experience Pack 1000.22632.1000.0

**详情**
![capture_20220727134632632](https://user-images.githubusercontent.com/70836772/181170902-01bcb76b-21a4-4236-9b31-6dacb0e3fc35.jpg)
在注册表中直接修改SystemUseLightTheme值为false后，任务栏颜色并未刷新，点击开始菜单后颜色更改
![capture_20220727134719976](https://user-images.githubusercontent.com/70836772/181171050-51cc9c90-b66f-427d-a471-a9ccbeb6756e.jpg)
文字颜色和图标并没有正确更改

**推测原因**
21H2版本中直接更改注册表可以成功更改系统颜色，但升级到22H2后出现颜色异常，推测微软在这次更新中一些组件的渲染机制发生了更改（任务栏目前修修补补f**k），目前尚不清楚系统设置中更改颜色的机制

**Comment by 6get-xiaofan** [comment]
我将尝试解决

**Comment by whtrys** [comment]
这个bug是微软的锅，在系统设置中手动更改为暗色也一样会有任务栏需要重刷新（即点击开始菜单）才能改变的bug

**Comment by oreomaker** [comment]
另一个软件的issue里面有一个参考，https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/424#issuecomment-1098550510，修改注册表的方法可能确实被弃用了

**Comment by 6get-xiaofan** [comment]
![image](https://user-images.githubusercontent.com/57002549/181865949-f8b38427-e520-4eb3-9a69-705933f216d8.png)
问题暂时关闭，等待微软修复，我也在虚拟机上测试了，目前最新22H2非最稳定版本，不建议为了体验新功能使用不稳定版本，我也会持续追踪微软的修复进展，非必要情况下不会使用注入强制刷新窗体。
