### ISSUE TITLE
日出日落模式 对地址的识别出现问题

### ISSUE THREAD

**Issue by guokelidehuanxiang** [Melon-Studio/DarkMode#5]
您好:
<img width="197" alt="image" src="https://user-images.githubusercontent.com/68645870/181263584-78bbc397-9f54-4487-b8c8-746cd48d1a99.png">
如图 我此刻在中国 但却显示为 其他国家 没有开代理

**Comment by 6get-xiaofan** [comment]
百度搜索IP，会显示你当前的位置，如果不是中国那说明不是软件的问题

**Comment by 6get-xiaofan** [comment]
这个显示没有影响，因为经纬度的调用是使用电脑的定位服务，ip的获取是其他方式，如果设置了日出日落模式，这个显示是没有影响的，可以忽略
![image](https://user-images.githubusercontent.com/57002549/181265872-6008d05b-8d49-4d8e-9104-d46d7b42ec41.png)

**Comment by whtrys** [comment]
建议**删除**此issue，有**隐私泄露**的问题
