### ISSUE TITLE
建议初次启动时显示提示窗口

### ISSUE THREAD

**Issue by Nobodies123** [Melon-Studio/DarkMode#8]
如题
大多数人下载之后打开发现没有窗口往往以为有问题，建议第一次打开的时候给个提示，或者提示修改默认设置，至少也要发一个气泡消息

**Comment by 6get-xiaofan** [comment]
已采纳，下个版本新增此功能

**Comment by 6get-xiaofan** [comment]
https://github.com/Melon-Studio/DarkMode/releases/tag/v1.6.5
